export const restaurantList = [
  {
    id: 1,
    resName: "Pizza Palace",
    cuisine: "Italian, Continental",
    rating: "4.5",
    costForTwo: "₹600 for two",
    deliveryTime: "30 mins",
  },
  {
    id: 2,
    resName: "Spice Route",
    cuisine: "Indian, North Indian",
    rating: "3.8",
    costForTwo: "₹450 for two",
    deliveryTime: "22 mins",
  },
  {
    id: 3,
    resName: "Sushi World",
    cuisine: "Japanese, Asian",
    rating: "4.7",
    costForTwo: "₹900 for two",
    deliveryTime: "35 mins",
  },
  {
    id: 4,
    resName: "Burger Hub",
    cuisine: "Fast Food, American",
    rating: "3.2",
    costForTwo: "₹350 for two",
    deliveryTime: "18 mins",
  },
  {
    id: 5,
    resName: "Green Bowl",
    cuisine: "Healthy, Salads",
    rating: "4.6",
    costForTwo: "₹500 for two",
    deliveryTime: "28 mins",
  },
  {
    id: 6,
    resName: "Tandoori Flames",
    cuisine: "Indian, Mughlai",
    rating: "3.5",
    costForTwo: "₹700 for two",
    deliveryTime: "26 mins",
  },
  {
    id: 7,
    resName: "Dragon Dynasty",
    cuisine: "Chinese, Sichuan",
    rating: "2.9",
    costForTwo: "₹550 for two",
    deliveryTime: "24 mins",
  },
  {
    id: 8,
    resName: "Street Bites",
    cuisine: "Street Food, Snacks",
    rating: "3.1",
    costForTwo: "₹200 for two",
    deliveryTime: "14 mins",
  },
  {
    id: 9,
    resName: "Royal Biryani House",
    cuisine: "Biryani, Hyderabadi",
    rating: "4.8",
    costForTwo: "₹650 for two",
    deliveryTime: "32 mins",
  },
  {
    id: 10,
    resName: "Cafe Mocha",
    cuisine: "Cafe, Desserts",
    rating: "4.0",
    costForTwo: "₹400 for two",
    deliveryTime: "20 mins",
  },
  {
    id: 11,
    resName: "MexiGo",
    cuisine: "Mexican",
    rating: "3.7",
    costForTwo: "₹550 for two",
    deliveryTime: "29 mins",
  },
  {
    id: 12,
    resName: "Kebab Junction",
    cuisine: "Mughlai, BBQ",
    rating: "3.3",
    costForTwo: "₹750 for two",
    deliveryTime: "34 mins",
  },
  {
    id: 13,
    resName: "South Spice",
    cuisine: "South Indian",
    rating: "4.2",
    costForTwo: "₹300 for two",
    deliveryTime: "17 mins",
  },
  {
    id: 14,
    resName: "Taste of Punjab",
    cuisine: "Punjabi, North Indian",
    rating: "3.9",
    costForTwo: "₹680 for two",
    deliveryTime: "31 mins",
  },
  {
    id: 15,
    resName: "Ocean Breeze Seafood",
    cuisine: "Seafood, Continental",
    rating: "3.0",
    costForTwo: "₹900 for two",
    deliveryTime: "36 mins",
  },
  {
    id: 16,
    resName: "Waffle Mania",
    cuisine: "Desserts, Cafe",
    rating: "4.4",
    costForTwo: "₹350 for two",
    deliveryTime: "19 mins",
  },
  {
    id: 17,
    resName: "Noodle Nest",
    cuisine: "Chinese, Thai",
    rating: "3.6",
    costForTwo: "₹500 for two",
    deliveryTime: "23 mins",
  },
  {
    id: 18,
    resName: "Bowl & Spoon",
    cuisine: "Healthy, Bowls",
    rating: "4.1",
    costForTwo: "₹550 for two",
    deliveryTime: "21 mins",
  },
  {
    id: 19,
    resName: "Chai Adda",
    cuisine: "Tea, Snacks",
    rating: "2.8",
    costForTwo: "₹150 for two",
    deliveryTime: "12 mins",
  },
  {
    id: 20,
    resName: "The Great Tiffin",
    cuisine: "Home Food, Indian",
    rating: "4.3",
    costForTwo: "₹300 for two",
    deliveryTime: "27 mins",
  },
];
